name: Basic Workflow
on:
  push:
    branches: feature/basic-workflow
jobs:
  do-things:
    name: Do things
    runs-on: ubuntu-latest
    steps:
      - name: "The thing I've Done"
        run: echo "I've done the thing"
